//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressBook.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressBook
    {
        public int AddressBookId { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string BusinessPhoneNumber { get; set; }
        public string Location { get; set; }
        public string Department { get; set; }
        public string EmailAddress { get; set; }
        public string Company { get; set; }
        public string Elias { get; set; }
    }
}
